---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniweb
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=foxyoab/mini-web-app
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^0\.[0-9]+\.[0-9]+-uat\..*
    argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'test'
    server: https://kubernetes.default.svc
  source:
    path: miniwebapp
    repoURL: https://github.com/Foxyoab/mini-web-app.git
    targetRevision: HEAD
    helm:
      parameters:
        - name: "image.repository"
          value: "foxyoab/mini-web-app"
        - name: "image.tag"
          value: "uat"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
